name: Test Changelog (PR Version)

# This workflow tests the PR version of the action against itself
# It only runs when action code is modified

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "action.yml"
      - "lib/**"
      - "package.json"
      - ".github/workflows/changelog-test.yml"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test-pr-version:
    runs-on: ubuntu-latest
    name: Test PR Version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Changelog with PR Version
        uses: ./  # Uses the local action code from this PR
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          changelog_path: "CHANGELOG.md"
          target_name: "context-ledger-test"
          version_increment: "auto"
          auto_commit: false  # Never auto-commit in test mode
          create_pr_suggestions: true
        continue-on-error: true

      - name: Report Test Status
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ steps.test-changelog.outcome }}';
            const body = status === 'success' 
              ? '✅ **Test Passed**: PR version of Context Ledger ran successfully!'
              : '⚠️ **Test Status**: PR version completed with status: ' + status;
            
            // Post a comment with test results
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body + '\n\n*This is a test run using the PR version of the action.*'
            });
